apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1eaf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1eaf
    app.kubernetes.io/part-of: tkrw-pr712-0075-0002-app
  name: devfile-sample-1eaf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1eaf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1eaf
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-1eaf@sha256:4211ef48cef574fbb9c1d709d2fe44921011c2c41ed879f983c04a5226eaed3e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
